USE commerceai;

CREATE TABLE clientes (
    IdCliente INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) DEFAULT NULL,
    Telefone VARCHAR(20) DEFAULT NULL,
    DataCadastro DATE DEFAULT (CURDATE()),
    Status ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    PRIMARY KEY (IdCliente),
    UNIQUE KEY (Email)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE produtos (
    IdProduto INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(150) NOT NULL,
    Descricao VARCHAR(300) DEFAULT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    Estoque INT NOT NULL,
    Categoria VARCHAR(50) DEFAULT NULL,
    CodigoBarras VARCHAR(30) DEFAULT NULL,
    SKU VARCHAR(20) DEFAULT NULL,
    DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    Ativo TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (IdProduto),
    UNIQUE KEY (CodigoBarras),
    UNIQUE KEY (SKU)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;
