USE commerceai;

CREATE TABLE clientes (
    IdCliente INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) DEFAULT NULL,
    Telefone VARCHAR(20) DEFAULT NULL,
    DataCadastro DATE DEFAULT (CURDATE()),
    Status ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    PRIMARY KEY (IdCliente),
    UNIQUE KEY (Email)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;
